def get_documents():
    return [
        """Neural networks are a set of algorithms, modeled loosely after the human brain, that are designed to recognize patterns. They interpret sensory data through a kind of machine perception, labeling or clustering raw input. The patterns they recognize are numerical, contained in vectors, into which all real-world data, be it images, sound, text or time series, must be translated.""",
        """Gradient descent is a first-order iterative optimization algorithm for finding a local minimum of a differentiable function. The idea is to take repeated steps in the opposite direction of the gradient (or approximate gradient) of the function at the current point, because this is the direction of steepest descent.""",
        """Transformers are a type of deep learning architecture introduced in 2017, primarily used in the field of natural language processing (NLP). Unlike recurrent neural networks (RNNs) which process data sequentially, transformers process entire sequences of data in parallel, drastically reducing training times. They rely heavily on a mechanism called self-attention, which weighs the significance of different parts of the input data differently.""",
        """Attention mechanisms in neural networks allow the model to focus on specific parts of the input sequence when producing a specific part of the output sequence. This is particularly useful in machine translation, where certain words in the input sentence are more relevant to predicting a specific word in the output sentence than others.""",
        """Retrieval-Augmented Generation (RAG) is a technique that enhances large language models (LLMs) by integrating external knowledge bases. Instead of relying solely on its internal training data, a RAG system first retrieves relevant documents from a vast corpus based on the user's query. These retrieved documents are then fed into the LLM as context, allowing it to generate more accurate, up-to-date, and domain-specific responses.""",
        """Embeddings are dense vector representations of data, such as words, sentences, or images, in a continuous vector space. By converting complex data into numerical vectors, machine learning models can process and compare them mathematically. Words with similar meanings will have embeddings that are close to each other in this space, capturing semantic relationships.""",
        """An Application Programming Interface (API) is a set of rules and protocols that allows different software applications to communicate with each other. It defines the methods and data formats that applications can use to request and exchange information. APIs abstract the underlying implementation, allowing developers to integrate external services or functionalities without needing to understand their internal workings.""",
        """Algorithms are step-by-step procedures or formulas for solving a problem. In computer science, an algorithm is an unambiguous specification of how to solve a class of problems. Algorithms can perform calculation, data processing, and automated reasoning tasks. They form the foundation of computer programming and software development.""",
        """Data structures are specialized formats for organizing, processing, retrieving and storing data. There are several basic and advanced types of data structures, all designed to arrange data to suit a specific purpose. Examples include arrays, linked lists, stacks, queues, trees, and graphs. Choosing the right data structure is crucial for the efficiency of an algorithm.""",
        """Operating system (OS) concepts include processes, threads, memory management, and file systems. A process is an instance of a computer program that is being executed. A thread of execution is the smallest sequence of programmed instructions that can be managed independently by a scheduler. Memory management involves controlling and coordinating computer memory, assigning portions to running programs to optimize overall system performance.""",
        """Compiler theory revolves around the principles and practices of designing and constructing compilers, which are programs that translate source code written in a high-level programming language into lower-level machine code or bytecode. This translation involves several phases, including lexical analysis, syntax analysis, semantic analysis, optimization, and code generation.""",
        """Natural Language Processing (NLP) is an interdisciplinary subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data. Tasks in NLP include speech recognition, natural language understanding, and natural language generation.""",
        """Computer vision is an interdisciplinary scientific field that deals with how computers can gain high-level understanding from digital images or videos. From the perspective of engineering, it seeks to understand and automate tasks that the human visual system can do. Tasks include image classification, object detection, and semantic segmentation."""
    ] * 4  # Multiplying by 4 to get ~52 chunks
